### ISSUE TITLE
Last update 29.09 - Let's encrypt issue?

### ISSUE THREAD

**Issue by mmd-osm** [Zverik/whosthat#7]
https://github.com/openstreetmap/openstreetmap-website/issues/3559 made me wonder if this page is still up and running. Last update date 29.09. could be related to https://twitter.com/OSM_Tech/status/1443622725021577222?cxt=HHwWjMC9qYjO44goAAAA maybe?

**Comment by Zverik** [comment]
Thank you for the report! Indeed, I forgot to update the scripts after the Let's Encrypt incident. Fixed it and restarted the updates. The database will be up-to-date in a few hours.
